### ISSUE TITLE
Issues since update - 1.3.1

### ISSUE THREAD

**Issue by mikesmith93** [tgomilar/paroller.js#30]
I ran NPM update to update the plugin to v1.3.1. This throws an error when I run npm start, see below:

> foundation-zurb-template@1.0.0 start /Users/mike/Documents/Design Work/Design work/Fort Productions/Website/build/templates
> gulp
module.js:557
    throw err;
    ^
Error: Cannot find module 'vinyl'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/gulp-util/index.js:2:9)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-zurb-template@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundation-zurb-template@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mike/.npm/_logs/2018-03-07T21_07_47_992Z-debug.log`

I have a live version of the site running v1.0 of the plugin and that has no issues.

**Comment by tgomilar** [comment]
This looks like Gulp/npm error. Try to delete all node modules and reinstall them. A command sequence like this would do: 
`npm cache clean`
`rm -Rf node_modules/`
`npm install`

Also check [this](https://github.com/mgechev/angular-seed/issues/1896) and [this solution](https://github.com/Polymer/polymer-starter-kit/issues/399).
